name: run maintest.py

on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:

  schedule:
    - cron: "9 8 7 6 *" #Runs at 08:09AM, every June 7th.
    #- cron: "*/5 * * * *" #Runs every 5 minutes.

permissions:
  checks: write
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run maintest.py
        env:
          keyw86w86: ${{ secrets.keyw86w86 }} #key for the Census API, activated
          keyluos86: ${{ secrets.keyluos86 }} #backup key
        run: python maintest.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
